version: '2.4' 
services:
  server:
    build:
      context: .\DayZDockerServer
      args:
        - steamlogin
        - steampasswd
        - steamguard
    isolation: process
    networks:
      app_net:
        ipv4_address: 172.16.238.99
networks:
  app_net:
    driver: nat
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1