version: '2.4' 
services:
  server:
    build:
      context: ./DayZDockerServer
      args:
        - steamlogin
        - steampasswd
        - steamguard
    volumes:
        - ./DayZProfiles:/DayZProfiles
        - ./DayZConfig:/DayZConfig
        - ./DayZMission:/DayZMission
volumes:
  DayZProfiles:
  DayZConfig:
  DayZMission: